### PR TITLE
Use PCRE-compatible CSON grammar

### PR DESCRIPTION
**Pull request by worldbeater**
We finally did this! This CSON grammar is PCRE compatible and so can be used both in Atom and in GitHub web interfaces. An old JSON-based grammar is less readable and less maintainable, so I decided to switch to CSON. Sources were taken from here: https://github.com/dotnet/csharp-tmLanguage/tree/master/grammars 

GitHub's highlighter was not highlighting source code correctly while PCRE does not support special characters in named group's names, such as a hyphen. So I got rid of them all using a simple [Python](https://www.python.org/) script.

This pull request closes these issues while GitHub highlighting now works as expected:
https://github.com/atom/language-csharp/issues/114
https://github.com/atom/language-csharp/issues/113
https://github.com/atom/language-csharp/issues/112

**Special thanks** to @hacklex for a great help with figuring out what was causing RegEx compatibility issues. It would be almost **impossible** to implement all these things without his assistance.

Thanks!

### CODE REVIEW

**Comment by worldbeater** [comment]
[Here is how the highlighting works now](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fworldbeater%2Flanguage-csharp%2Faf991b07b724c7f42a4fde9800143d31fb68c7fc%2Fgrammars%2Fcsharp.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Fworldbeater%2Fc7cb51a1f6b07d5b8a46d3df5983d047%2Fraw%2F918acf82490816ea8d9a36f0bb9dccee8c2e6c97%2FFeedbackFormViewModel.cs&code=). All bugs are gone, types and method calls get highlighted.

image

**Comment by damieng** [comment]
That's great!  Thanks for this.

I need a day or two to figure out how to get the atom and github versions to co-exist nicely in this repo - right now what you did will make github.com work but will break our Atom text editor as it isn't PCRE based and also uses this repo.

**Comment by worldbeater** [comment]
@damieng I suppose this grammar will also play well with Atom editor, but not sure. The conversion we've done can be described in two steps:
1. JSON grammar was replaced with CSON one to improve readability 
(CSON supports line breaks, spacing and is less verbose!)
2. Hyphens in named groups were completely removed. For example this:
```(?<type-args>\\s*<(?:[^<>]|\\g<type-args>)+>\\s*)?```
Became this:
```(?<typeargs>\\s*<(?:[^<>]|\\g<typeargs>)+>\\s*)?```
Perhaps, Oniguruma should also support it, as named groups syntax is the same.

**Comment by worldbeater** [comment]
Just tested the new grammar in **Atom** editor by using `atom --dev` and `apm develop language-csharp`. I simply replaced an old JSON grammar with a newer one that does not contain hyphens in group names and that uses CSON format. This is the output:

image

This means an old grammar can be simply replaced with a newer one from this pull request and both GitHub and Atom highlighters would work as expected, no need for extra repositories!

**Comment by damieng** [comment]
Awesome!  Thanks for this.

**Comment by kasper3** [comment]
@worldbeater, thank you! Would it make sense that we add this script to upstream 
if @DustinCampbell and @damieng agree as well, so there is one source of truth or point of failure? :)

**Comment by damieng** [comment]
I was going to suggest to Dustin that perhaps we just run it one-time upstream to convert the names to not have dashes and maintain it like that going forward so it continues to work for github.com as well as all the other editors.  

The regex named groups are purely internal so it shouldn't have any affect on anyone else.

**Comment by damieng** [comment]
I'm still seeing some issues with linguist - specifically things that should be entity names are coming through as keywords.  Did you base the grammar on the one here in the repo or one upstream?

For comparison:

**Linguist**

image

**Atom**

image

**Comment by damieng** [comment]
Okay, I guess you took from upstream - I had to apply our two lines of changes we need on top to get the entity name highlighting working.  

Lightshow now showing correctly :)

image

**Comment by worldbeater** [comment]
@damieng very nice! The only thing left that bothers me is that for function or constructor parameters type names and variable names are [highlighted using the same color now](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-csharp%2Fmaster%2Fgrammars%2Fcsharp.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fworldbeater%2FmyFeed%2Fblob%2Fmaster%2FmyFeed%2FServices%2FBackgroundService.cs&code=).

image

Is there anything we can do with this? Maybe for variable names black color can be used, not sure exactly.

**Comment by damieng** [comment]
I'll take a look at that tonight. I think I know what's causing it and it will be another tweak on our side.

**Comment by worldbeater** [comment]
Maybe this can help. There are four lines in this grammar that are responsible for parameters highlighting. Each line uses **entity.name.variable.parameter.cs** name: [method parameters](https://github.com/atom/language-csharp/blob/master/grammars/csharp.cson#L3148), [named arguments](https://github.com/atom/language-csharp/blob/master/grammars/csharp.cson#L3193), [anonymous method expressions](https://github.com/atom/language-csharp/blob/master/grammars/csharp.cson#L3486) and [lambda parameters](https://github.com/atom/language-csharp/blob/master/grammars/csharp.cson#L3614). In language-java repository they use **variable.parameter.java**, so we can use **variable.parameter.cs**. I'll test and update this message to see what will happen.

**Comment by worldbeater** [comment]
Well, if we use [language-java](https://github.com/atom/language-java/blob/master/grammars/java.cson#L504) approach, we will get this [fancy highlighting](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=http%3A%2F%2F149.154.70.247%2Fcsharp.cson.txt&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fworldbeater%2FmyFeed%2Fblob%2Fmaster%2FmyFeed%2FServices%2FBackgroundService.cs&code=).
image

**Comment by worldbeater** [comment]
@damieng need your help with implementing black highlighting for C# fields, variables, and parameters. [Here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=http%3A%2F%2F149.154.70.247%2Fcsharp.cson.black.txt&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fworldbeater%2FmyFeed%2Fblob%2Fmaster%2FmyFeed%2FServices%2FBackgroundService.cs&code=) I achieve this by changing **entity.name.variable.parameter.cs** and [other phrases](https://github.com/atom/language-csharp/pull/116#issuecomment-382527964) to **no.cs** so it can't find the color key and defaults to black. But this doesn't seem to be an elegant solution :(

**Pull request merged**
