### PR TITLE
Support interpolated strings

### LINKED ISSUE #43: [C#] syntax coloring breaks down with interpolated strings
_From @jumpinjackie on December 2, 2015 6:40_

Using VSCode 0.10.3

The C# syntax coloring breaks down when interpolated strings are involved.

Example code

``` c#
    namespace Test
    {
        public class Foo
        {
            static string AddTableName(string suffix) => $"Bar{suffix}_ADD";

            static string ModTableName(string suffix) => $"Bar{suffix}_MOD";

            static string DelTableName(string suffix) => $"Bar{suffix}_DEL";
        } 
    }
```

VSCode screenshot

capture

_Copied from original issue: Microsoft/vscode#900_

### PR DESCRIPTION
**Pull request by 50Wliu**
~~Fixes #43~~

Note: I was not able to test this (yet).  It probably doesn't even fix anything.

### CODE REVIEW

**Comment by 50Wliu** [comment]
While this now works, it actually doesn't fix #43.  The bigger issue is that lambdas are entirely unsupported, which I'm working on now.

**Comment by lee-dohm** [comment]
> which I'm working on now.

Are you going to open a separate PR for the lambdas and this is ready to review now? (Sorry, just clarifying ... brain too full :grinning:)

**Comment by 50Wliu** [comment]
Yeah, this is ready for review.  Lambdas...might take a while.  Trying to copy/paste over as much as I can from language-javascript but there's a lot to change :(.

**Comment by lee-dohm** [comment]
This looks ok to me but I haven't used C# in a few years and am not up to date on the new string interpolation stuff.

**Comment by 50Wliu** [comment]
I just followed the spec: https://msdn.microsoft.com/en-us/library/dn961160.aspx?f=255&MSPPError=-2147217396.  Hopefully that covers everything :laughing:.

**Comment by shiftkey** [comment]
@lee-dohm I can kick the tires on this PR over the weekend if you'd like a +1 on this

**Comment by lee-dohm** [comment]
I'd appreciate that @shiftkey :grinning:

**Comment by shiftkey** [comment]
For reference, this is an example:

```csharp
Console.WriteLine($"Name = {name}, hours = {hours:hh}")
```

**Comment by jamesqo** [comment]
Any progress on this yet?

By the way, I hope you also take into consideration that string interpolation can be combined with verbatim literals, e.g.

```csharp
string message = $@"{name} exclaimed ""Hello, world!""";
```

**Pull request closed without merging**
