### PR TITLE
Use grammar from Microsoft

### PR DESCRIPTION
**Pull request by damieng**
Use the Microsoft-supported grammar for C# from https://github.com/dotnet/csharp-tmLanguage

### CODE REVIEW

**Comment by damieng** [comment]
Rather than wait for upstream changes to handle the storage.type.cs colorization issues made two small changes so 99% of our class names still looks right in Atom and on GitHub.com

**Comment by damieng** [comment]
@worldbeater thanks for nudge on this and let me know if you see any weirdness with this grammar before we ship.

**Comment by damieng** [comment]
Fixes #88 #93 #96 #97 #99 #100 #103 #105 #106 #107

**Comment by worldbeater** [comment]
Unable to detect any problems in my projects -- everything seems to work as expected! Most bugs are gone! Among them are: https://github.com/atom/language-csharp/issues/107 https://github.com/atom/language-csharp/issues/100 https://github.com/atom/language-csharp/issues/96 https://github.com/atom/language-csharp/issues/88 and many others!

image

Seems to be production-ready!

**Comment by damieng** [comment]
Tempted to bump the package from 0.14.x to 1.0.0 ;-)

**Pull request merged**
