### PR TITLE
Remove redundant `source` scopes

### LINKED ISSUE #35: Unnecessary `source` scopes
In other languages there is no `source` scopes for languages symbols. I guess it might cause problems if packages would use scopes.

image

### PR DESCRIPTION
**Pull request by MaximSokolov**
Fixes #35

### CODE REVIEW

**Comment by 50Wliu** [comment]
@simurai

**Comment by MaximSokolov** [comment]
Requires changes after #36

**Comment by MaximSokolov** [comment]
Done

**Comment by simurai** [comment]
I think this change is good. AFAIK, `source` is only used to select a language, like [`.source.cs`](https://github.com/atom/one-dark-syntax/blob/master/styles/languages/cs.less#L1). But not for the rest, right?

**Comment by MaximSokolov** [comment]
> I think this change is good. AFAIK, source is only used to select a language, like .source.cs. But not for the rest, right?

You are correct. I guess `source` exist because of embedded code:
```
<script type="text/javascript">
	// source.js.embedded 
</script>
```

**Comment by simurai** [comment]
@MaximSokolov ok, thanks for cleaning it up.

**Pull request merged**
